kind: Namespace
apiVersion: v1
metadata:
  name: mygraph
  labels:
    name: mygraph
    polycube.network/sidecar: enabled
  annotations:
    astrid.io/deployments: "[\"nginx\", \"nodejs\", \"apache\"]"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mygraph
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 
    name: nginx-app-80-port
  clusterIP: 
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: mygraph
  labels:
    app: nodejs
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 
    name: nodejs-app-port
  clusterIP: 
  selector:
    app: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: mygraph
  labels:
    app: apache
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 
    name: apache-app-port
  clusterIP: 
  selector:
    app: apache
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  namespace: mygraph
  annotations:
    astrid.io/security-components: "[\"firewall\"]"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        polycube.network/sidecar: enabled
      labels:
        app: nginx
    spec:
      containers:
      - name: simple-service
        image: asimpleidea/simple-service:latest
        env:
        - name: APP_NAME
          value: "nginx"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nodejs
  namespace: mygraph
  annotations:
    astrid.io/security-components: "[\"firewall\"]"
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  template:
    metadata:
      annotations:
        polycube.network/sidecar: enabled
      labels:
        app: nodejs
    spec:
      containers:
      - name: simple-service
        image: asimpleidea/simple-service:latest
        env:
        - name: APP_NAME
          value: "nodejs"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: apache
  namespace: mygraph
  annotations:
    astrid.io/security-components: "[\"firewall\"]"
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      annotations:
        polycube.network/sidecar: enabled
      labels:
        app: apache
    spec:
      containers:
      - name: simple-service
        image: asimpleidea/simple-service:latest
        env:
        - name: APP_NAME
          value: "apache"
        ports:
        - containerPort: 80